"""
Configuration file for Pneumonia Detection AI System
"""

import os
from dotenv import load_dotenv

load_dotenv()

# MODEL CONFIGURATION
MODEL_PATH = 'resnet50_pneumonia_classifier.pth'
NUM_CLASSES = 2
IMAGE_SIZE = 224
CLASS_NAMES = ['Normal', 'Pneumonia']
NORM_MEAN = [0.485, 0.456, 0.406]
NORM_STD = [0.229, 0.224, 0.225]

# GROK API CONFIGURATION
GROK_API_KEY = os.getenv("XAI_API_KEY")
GROK_API_URL = "https://api.x.ai/v1/chat/completions"
GROK_MODEL_NAME = "grok-4-fast-non-reasoning"

# RAG CONFIGURATION
KB_PATH = "web_medical_kb.pkl"
INDEX_PATH = "web_faiss_index.bin"
TEMP_GRAD_CAM_PATH = "temp_grad_cam_overlay.png"
TEMP_IMAGE_PATH = "temp_original_image.png"

MEDICAL_URLS = [
    "https://www.mayoclinic.org/diseases-conditions/pneumonia/symptoms-causes/syc-20354204",
    "https://medlineplus.gov/pneumonia.html",
    "https://www.cdc.gov/pneumonia/index.html",
    "https://my.clevelandclinic.org/health/diseases/4471-pneumonia",
    "https://www.who.int/news-room/fact-sheets/detail/pneumonia",
    "https://www.healthline.com/health/pneumonia"
]

MAX_PAGES_TO_CRAWL = 20
REQUEST_TIMEOUT = 10
EMBEDDING_MODEL_NAME = 'all-MiniLM-L6-v2'
TOP_K_RETRIEVAL = 5
EMBEDDING_DIMENSION_FALLBACK = 100

# GUI CONFIGURATION
WINDOW_TITLE = "AI Pneumonia Detection System"
WINDOW_WIDTH = 1500
WINDOW_HEIGHT = 950

# PDF & TEXT PROCESSING
TEXT_REPLACEMENTS = {
    "—": "-", "–": "-", "'": "'", "'": "'",
    """: '"', """: '"', "…": "...", "•": "*", "°": " deg",
}

MIN_CONTENT_LENGTH = 50
MAX_CONTENT_LENGTH = 1000

# FALLBACK KNOWLEDGE BASE
FALLBACK_MEDICAL_KNOWLEDGE = [
    {"id": 1, "title": "Pneumonia Diagnostic Standards",
     "content": "Pneumonia is lung inflammation caused by pathogens. Main symptoms include cough, fever, and respiratory difficulty. Chest X-ray examination is key for diagnosis.",
     "url": "fallback"},
    {"id": 2, "title": "Normal Chest X-ray Features",
     "content": "Normal chest X-rays show clear lung fields, normal heart size, and no abnormal shadows. Ribs are symmetrically distributed.",
     "url": "fallback"},
    {"id": 3, "title": "Pneumonia X-ray Manifestations",
     "content": "Pneumonia patients' X-rays show lung infiltration, consolidation shadows, and possible bronchial air signs. Commonly found in lower lobes.",
     "url": "fallback"}
]

PDF_DISCLAIMER = (
    "Disclaimer: This report is generated by an AI model and is for informational purposes only. "
    "It is not a substitute for professional medical advice, diagnosis, or treatment. "
    "Always seek the advice of a qualified healthcare provider for any medical questions or conditions. "
    "The AI model's output should be validated by a human expert."
)
